### ISSUE TITLE
Partially Paid / Underpaid

### ISSUE THREAD

**Issue by astupidmoose** [jaimehgb/Mycelium-Opencart-plugin#6]
Opencart is not accepting any calls from Mycelium gear with "Partially Paid" and has a status of "Callback response status: 302"

Perhaps we need an additional "Order Statuses" field in the extension settings for underpaid if this is possible? 

Right now, underpaid orders remain "Missing orders" in opencart.

**Comment by jaimehgb** [comment]
Yep, currently the plugin ignores the callbacks sent with underpaid transactions. At least until another transaction is made to the same address with the remaining amount (haven't tested this but if mycelium sends a new callback if the payment is made in more than 1 part it should work).

https://github.com/jaimehgb/Mycelium-Opencart-plugin/blob/master/upload/catalog/controller/payment/mycelium.php#L257

Case 3 (missing) is the one which would handle underpaid orders. I'll fix that tomorrow (hopefully :P )

**Comment by astupidmoose** [comment]
Transactions still do not seem to be receiving the callbacks when "partially paid". Perhaps this is an issue with mycelium not sending the callback until the status is set to "underpaid"?

Partially paid is set on mycelium for X minutes until order expires, however it would be nice if the partial is considered the underpayment. Allowing customers to top up their balance. 

When I check the transaction in mycelium, there is no data in Callback response field.
